market_data:
  retry_backoff_ms: 250
  resubscribe_sec: 300
  feeds: ["binance", "coinbase", "bybit", "oanda"]
alpha:
  weights: { momentum: 0.5, mean_reversion: 0.3, breakout: 0.2, sentiment: 0.1 }
  reweight_cron: "10 0 * * *"
  nlp_model: "llama3-lora-trading"
risk:
  max_trade_risk_pct: 0.3
  daily_drawdown_pct: 5.0
  slippage_limit_pct: 0.2
  hard_kill_pct: 7.0
exec:
  maker_rebate_threshold_bps: 1.0
  fallback_on_reject: true
sentiment:
  score_feed: "risingwave://sentiment_30m"
  news_apis: ["newsapi.org", "twitter", "reddit"]
meta_governor:
  enable_rl: true
  retrain_cron: "5 1 * * *"
