apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maxx-frontend
  template:
    metadata:
      labels:
        app: maxx-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/$PROJECT_ID/maxx-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: maxx-frontend
spec:
  type: LoadBalancer
  selector:
    app: maxx-frontend
  ports:
  - name: http
    port: 80
    targetPort: 3000
