apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: maxx-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: myrepo/backend:latest # replaced by deploy_gke.sh
        env:
        - name: ORCH_URL
          value: http://orchestrator:8080
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: maxx-ai
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
