apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: maxx-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/${GCP_PROJECT}/maxx-frontend:${IMAGE_TAG}
          env:
            - name: NEXT_PUBLIC_WS_URL
              value: ws://backend:8000/ws/agents
          ports:
            - containerPort: 3000
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: maxx-ai
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
