apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: maxx-ai
  annotations:
    cosign.sigstore.dev/message: "verified"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: myrepo/frontend:latest # replaced by deploy_gke.sh
        env:
        - name: NEXT_PUBLIC_WS_URL
          value: ws://backend:8001/ws/agents
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: maxx-ai
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
