apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama3
  namespace: maxx-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama3
  template:
    metadata:
      labels:
        app: llama3
    spec:
      containers:
        - name: llama3
          image: ghcr.io/vllm/vllm-engine:2.0
          resources:
            limits:
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8000
          securityContext:
            readOnlyRootFilesystem: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: llama3
  namespace: maxx-ai
spec:
  selector:
    app: llama3
  ports:
    - port: 8000
      targetPort: 8000
