apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: maxx-ai
  annotations:
    cosign.sigstore.dev/message: "verified"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: myrepo/orchestrator:latest # replaced by deploy_gke.sh
        env:
        - name: MODEL_ENDPOINT
          value: "http://llama3:8000/v1"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          readOnlyRootFilesystem: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: maxx-ai
spec:
  selector:
    app: orchestrator
  ports:
  - port: 8080
    targetPort: 8080
