apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: maxx-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: gcr.io/${GCP_PROJECT}/maxx-orchestrator:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: maxx-ai
spec:
  selector:
    app: orchestrator
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
